---
name: Build

on:
  pull_request:
    branch: master

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build code
    steps:

    - name: Source checkout
      uses: actions/checkout@v2.3.2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Cache sonar plugins
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-sonar-

    - name: Check source files License header
      run: mvn license:check -B -ff

    - name: Validate testing json files
      run: mvn yaml-json-validator:validate -B -ff

    - name: Test, compile, package, and verify
      run: mvn verify -B -ff

    - name: Checkstyle checker
      run: mvn checkstyle:check -B -ff

    - name: PMD checker
      run: mvn pmd:check -B -ff

    - name: CPD checker
      run: mvn pmd:cpd-check -B -ff

    - name: SpotBugs checker
      run: mvn spotbugs:check -B -ff

    - name: Create javadoc files
      run: mvn javadoc:javadoc -B -ff

    - name: SonarCloud scan and report
      run: mvn sonar:sonar -B -ff
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
