---
name: Shabbat Times Alexa Skill Java CI

on:
  push:
    branch: "master"
  pull_request:
    branch: "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check source files License header
      run: mvn license:check -B -ff
    - name: Checkstyle checker
      run: mvn checkstyle:check -B -ff
    - name: PMD checker
      run: mvn pmd:check -B -ff
    - name: CPD checker
      run: mvn pmd:cpd-check -B -ff
    - name: Validate json files
      run: mvn yaml-json-validator:validate -B -ff
    - name: Build and verify JaCoCo metrics
      run: mvn verify -B -ff
#    - name: Create javadoc files
#      run: mvn javadoc:javadoc -B -ff
